[build]
  # Directory to change to before starting a build. 
  # This is where we will look for package.json/.nvmrc/etc.
  base = "tarot"
  publish= "/build"
  command = "yarn build"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200